{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c17c03d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import pandas as pd\n",
    "from selenium import webdriver\n",
    "from time import sleep\n",
    "from datetime import datetime, timedelta, date\n",
    "from email.mime.multipart import MIMEMultipart\n",
    "from email.mime.text import MIMEText\n",
    "import smtplib\n",
    "import os\n",
    "from dotenv import load_dotenv\n",
    "load_dotenv()\n",
    "from openai import OpenAI\n",
    "\n",
    "SENDER_EMAIL = os.getenv('SENDER_EMAIL')\n",
    "GMAIL_KEY = os.getenv('GMAIL_KEY')\n",
    "MAIL_TO = os.getenv('MAIL_TO')\n",
    "OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')\n",
    "\n",
    "client = OpenAI(\n",
    "    api_key=os.getenv(\"OPENAI_API_KEY\"),\n",
    "    organization=os.getenv(\"organization\"),      # 加入你的組織 ID\n",
    "    project= os.getenv(\"project_id\")           # 加入你的專案 ID（僅適用於 project key）\n",
    ")\n",
    "\n",
    "def summarize_text(text):\n",
    "    try:\n",
    "        response = client.chat.completions.create(\n",
    "            model=\"gpt-4o\",\n",
    "            messages=[\n",
    "                {\"role\": \"system\", \"content\": \"你是一個專業的文章摘要助手，請提取文章的重點。\"},\n",
    "                {\"role\": \"user\", \"content\": f\"請幫我摘要以下文章的重點, 200字以內：{text}\"}\n",
    "            ],\n",
    "            temperature=0.5,\n",
    "            max_tokens=150\n",
    "        )\n",
    "        return response.choices[0].message.content.strip().replace('\\n', ' ')\n",
    "    except Exception as e:\n",
    "        print(f\"⚠️ GPT 摘要錯誤：{e}\")\n",
    "        return \"❌ 摘要失敗\"\n",
    "### -------- 共用設定 -------- ###\n",
    "def init_driver():\n",
    "    options = webdriver.ChromeOptions()\n",
    "    options.add_experimental_option('excludeSwitches', ['enable-automation']) #隱藏chrome 正受到\n",
    "    options.add_argument('--headless')               # 加上這行\n",
    "    options.add_argument('--disable-gpu')            # 加上這行\n",
    "    options.add_argument('--window-size=1920,1080')  # 加上這行\n",
    "    driver = webdriver.Chrome(options=options)\n",
    "    driver.maximize_window()\n",
    "    return driver\n",
    "### -------- 共用設定查詢間隔 -------- ###\n",
    "startday = date.today() - timedelta(days=1)\n",
    "top_keywords = ['銀行股份有限公司', '證券', '期貨', '投信', '保險', '金融控股', '金控', '銀行', '投顧']\n",
    "\n",
    "### -------- 爬金管會主網站 -------- ###\n",
    "def crawl_main_site(driver):\n",
    "    url = 'https://www.fsc.gov.tw/ch/home.jsp?id=131&parentpath=0,2'\n",
    "    driver.get(url)\n",
    "    driver.implicitly_wait(5)\n",
    "\n",
    "    newlist = []\n",
    "    for item in range(2, 17):\n",
    "        try:\n",
    "            date_text = driver.find_element('css selector', f'#messageform > div.newslist > ul > li:nth-child({item}) > span.date').text\n",
    "            unit_text = driver.find_element('css selector', f'#messageform > div.newslist > ul > li:nth-child({item}) > span.unit').text\n",
    "            link = driver.find_element('css selector', f'#messageform > div.newslist > ul > li:nth-child({item}) > span.title > a')\n",
    "            title_text = link.get_attribute('title')\n",
    "            href = link.get_attribute('href')\n",
    "            date_obj = datetime.strptime(date_text, \"%Y-%m-%d\").date()\n",
    "            link.click()\n",
    "            date_re = driver.find_element('#ap > div.pageview > div > ul > li:nth-child(2) > span').text\n",
    "            date_re = date_re[-10:]\n",
    "            date_obj = datetime.strptime(date_text, \"%Y-%m-%d\").date()\n",
    "            date_obj_re = datetime.strptime(date_re, \"%Y-%m-%d\").date()\n",
    "            title = driver.find_element('css selector', '#ap > div.maincontent > div.subject > h3').text\n",
    "            content = driver.find_element('css selector', '#ap > div.maincontent > div.page-edit ').text\n",
    "            driver.back()\n",
    "            if date_obj_re > date_obj :\n",
    "                date_obj = date_obj_re\n",
    "            if date_obj >= startday:\n",
    "                try:\n",
    "                    summary = summarize_text(content)\n",
    "                except Exception as e:\n",
    "                    summary = \"❌ 摘要失敗\"\n",
    "                    print(f\"⚠️ GPT 摘要錯誤：{e}\")\n",
    "\n",
    "                newlist.append({\n",
    "                    '編號': len(newlist) + 1,\n",
    "                    '發布日期': date_text,\n",
    "                    '資料來源': unit_text,\n",
    "                    '標題': f'<a href=\"{href}\" target=\"_blank\">{title}</a>',\n",
    "                    '內容': content,\n",
    "                    '摘要': summary\n",
    "                })\n",
    "        except Exception as e:\n",
    "            continue\n",
    "    return pd.DataFrame(newlist) if newlist else pd.DataFrame()\n",
    "\n",
    "\n",
    "### -------- 爬三個子網站 -------- ###\n",
    "def crawl_sub_sites(driver):\n",
    "    url_list = [\n",
    "        'https://www.sfb.gov.tw/ch/home.jsp?id=104&parentpath=0,2,102',\n",
    "        'https://www.banking.gov.tw/ch/home.jsp?id=550&parentpath=0,524,547',\n",
    "        'https://www.ib.gov.tw/ch/home.jsp?id=264&parentpath=0,2,262']\n",
    "    \n",
    "    burea_list = ['證期局', '銀行局', '保險局']\n",
    "    output = []\n",
    "\n",
    "    for i in range(3):\n",
    "        url = url_list[i]\n",
    "        bureau = burea_list[i]\n",
    "        driver.get(url)\n",
    "        driver.implicitly_wait(5)\n",
    "\n",
    "        for item in range(5, 33, 2):\n",
    "            try:\n",
    "                date_text = driver.find_element('css selector', f'#messageform > div:nth-child(7) > div:nth-child({item}) > div.pdate1').text\n",
    "                title_element = driver.find_element('css selector', f'#messageform > div:nth-child(7) > div:nth-child({item}) > div.ptitle1 > a')\n",
    "                title_text = title_element.text\n",
    "                href = title_element.get_attribute('href')\n",
    "                date_obj = datetime.strptime(date_text, \"%Y-%m-%d\").date()\n",
    "                title_element.click()\n",
    "                sleep(1)\n",
    "\n",
    "                content = driver.find_element('css selector', '#maincontent > div.page_content > div:nth-child(2)').text\n",
    "                title = driver.find_element('css selector', '#maincontent > div:nth-child(1) > h3').text\n",
    "                sleep(2)\n",
    "                #抓取更新日期\n",
    "                pageview_text = driver.find_element('css selector', '#maincontent > div.pageview').text\n",
    "                updated_match = pageview_text[-10:]\n",
    "    \n",
    "                driver.back()\n",
    "                sleep(2)\n",
    "                updated_date = datetime.strptime(updated_match, \"%Y-%m-%d\").date()\n",
    "                if date_obj >= startday and any(keyword in title_text for keyword in top_keywords):\n",
    "                    try:\n",
    "                        summary = summarize_text(content)\n",
    "                    except Exception as e:\n",
    "                        summary = \"❌ 摘要失敗\"\n",
    "                        print(f\"⚠️ GPT 摘要錯誤：{e}\")\n",
    "                    output.append({'資料來源': bureau,\n",
    "                                   '編號': len(output) + 1,\n",
    "                                   '發布日期': date_text,\n",
    "                                   '標題': f'<a href=\"{href}\" target=\"_blank\">{title}</a>',\n",
    "                                   '內容': content,\n",
    "                                   '摘要': summary})\n",
    "            except Exception:\n",
    "                continue\n",
    "\n",
    "    return pd.DataFrame(output) if output else pd.DataFrame()\n",
    "\n",
    "\n",
    "### -------- Email 寄送功能 -------- ###\n",
    "\n",
    "def send_email(df, title):\n",
    "    if df.empty:\n",
    "        print(f\"📭 無{title}，已略過寄信\")\n",
    "        return  # 中止函數，不發送 email\n",
    "\n",
    "    # 以下為原本的 email 寄送內容（略）\n",
    "    from email.mime.multipart import MIMEMultipart\n",
    "    from email.mime.text import MIMEText\n",
    "    import smtplib\n",
    "\n",
    "    msg = MIMEMultipart()\n",
    "    msg['Subject'] = title\n",
    "    msg['From'] = SENDER_EMAIL\n",
    "    msg['To'] = MAIL_TO\n",
    "    df['內容'] = df['內容'].str.replace('\\n', '<br>')\n",
    "    html_content = f\"\"\"\n",
    "        <html>\n",
    "        <head>\n",
    "            <style>\n",
    "            table {{\n",
    "                border-collapse: collapse;\n",
    "                width: 100%;\n",
    "                margin: 20px 0; }}\n",
    "           \n",
    "            th {{\n",
    "                background-color: #1a237e;\n",
    "                color: white;\n",
    "                text-align: center;\n",
    "                padding: 12px;\n",
    "                border: 1px solid #ddd;}}\n",
    "            \n",
    "            td {{\n",
    "                border: 1px solid #ddd;\n",
    "                padding: 12px;\n",
    "                text-align: left;\n",
    "                vertical-align: top;\n",
    "                white-space: pre-line;}}\n",
    "            \n",
    "            tr:nth-child(even) {{\n",
    "                background-color: #f2f2f2; }}\n",
    "           \n",
    "            h3 {{text-align: center;\n",
    "                color: #333;\n",
    "                margin: 20px 0;}}\n",
    "                \n",
    "            \n",
    "            </style>\n",
    "        </head>\n",
    "        <body>\n",
    "            <h3>{title}</h3>\n",
    "            {df.to_html(index=False, escape=False)}\n",
    "        </body>\n",
    "        </html>\"\"\"\n",
    " \n",
    "    msg.attach(MIMEText(html_content, 'html', 'utf-8'))\n",
    "\n",
    "    try:\n",
    "        smtp_server = smtplib.SMTP('smtp.gmail.com', 587)\n",
    "        smtp_server.starttls()\n",
    "        smtp_server.login(SENDER_EMAIL, GMAIL_KEY)\n",
    "  # 建議放進環境變數或 .env 檔\n",
    "        smtp_server.send_message(msg)\n",
    "        smtp_server.quit()\n",
    "        print(f'✅ 郵件發送成功：{title}')\n",
    "    except Exception as e:\n",
    "        print(f'❌ 郵件發送失敗：{e}')\n",
    "\n",
    "\n",
    "### -------- 主程式 -------- ###\n",
    "def main():\n",
    "    driver = init_driver()\n",
    "\n",
    "    # 主站（重大裁罰）\n",
    "    df_main = crawl_main_site(driver)\n",
    "    send_email(df_main, '金管會重大裁罰')\n",
    "\n",
    "    # 三局（非重大裁罰）\n",
    "    df_sub = crawl_sub_sites(driver)\n",
    "    send_email(df_sub, '金管會非重大裁罰')\n",
    "\n",
    "    driver.quit()\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
