name: Daily Run

on:
  schedule:
    - cron: '0 9,21 * * *'  # 每天的 UTC 時間 00:00 執行（台灣時間早上 8 點）
  workflow_dispatch:     # 允許手動執行

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # checkout the repository content
        uses: actions/checkout@v3

      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # install the python version needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create .env file
        run: |
          echo "SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}" >> .env
          echo "GMAIL_KEY=${{ secrets.GMAIL_KEY }}" >> .env
          echo "MAIL_TO=${{ secrets.MAIL_TO }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Run script
        run: python3 craw_mail.py  # 替換成你的程式檔名
