name: Daily Run

on:
  schedule:
    - cron: '0 20 * * *'  # 每天的 UTC 時間 20:00 執行（台灣時間早上 4 點）
  workflow_dispatch:     # allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # checkout the repository content
        uses: actions/checkout@v3

      - name: Set up Python # install the required python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: Install dependencies # install the required dependencies
        run: | 
          python -m pip install --upgrade pip  # upgrade pip to the newest version
          pip install -r requirements.txt  # install the required packages
          
      - name: Create .env file #  put the environment variables in a .env file
        run: |
          echo "SENDER_EMAIL=${{ secrets.SENDER_EMAIL }}" >> .env
          echo "GMAIL_KEY=${{ secrets.GMAIL_KEY }}" >> .env
          echo "MAIL_TO=${{ secrets.MAIL_TO }}" >> .env
          echo "RECIPIENT_EMAIL=${{ secrets.MAIL_TO_LAW }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: Run script
        run: |
          python3 craw_mail.py 
          python3 newrelsealaw.py
          python3 fsb_releseday.py # the file that you want to run
      
      
